name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 👈 your default branch

permissions:
  contents: write  # required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build static export
      - name: Build Next.js static site
        run: npm run build

      # 5️⃣ Add .nojekyll to allow _next/ assets on GitHub Pages
      - name: Add .nojekyll file
        run: touch out/.nojekyll

      # 6️⃣ Deploy the /out folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
